### ISSUE TITLE
Issue with page

### ISSUE THREAD

**Issue by rogerg1967** [DNNCommunity/DNN.Blog#72] opened 2016-03-07 18:19 UTC
Hi, i have setup a list of blogs. I have set the template to display 9 per page. Currently it has 7 on the first page. 7 on the second page replicating the last post from the previouse page as the first post on the next page. 6 posts on the third page, 7 on the fourth page and 7 on the last page repeating in the same way as the first 2 pages.

At no point do i get a consistency or 9 per page. I have just upgraded to use 6.2.2 on dnn 7.4.1

any ideas what is going wrong?

**Comment by mrswoop** [comment] 2016-03-28 23:45
Roger, if you want to send me your template I'll try it on my blogs to see if I can replicate the problem? You can reach me at scott -at- tough -dot- net

**Comment by donker** [comment] 2016-07-17 14:57
I'm not sure how you've set up the other modules to start displaying where the former left off. Can you elaborate?

**Comment by valadas** [comment] 2018-10-28 04:43
Looks like a duplicate of #60 , I could not reproduce on latest build, if you can still reproduce on latest build, please reopen an issue

**Closed by valadas** 2018-10-28 04:43 UTC
