### ISSUE TITLE
Issue with page sizes for list view.

### ISSUE THREAD

**Issue by rogerg1967** [DNNCommunity/DNN.Blog#60] opened 2015-12-02 13:39 UTC
Hi, 
I have a very odd issue with the page size on bloglist. the number of posts is not the same as set in the template settings. I want it to show 9 per page (3 rows of 3) On page 1 I have 5 posts on page 2 I have 8 on page 3 I have 9. To get it to show 9 on the first page I have to set the page size to 14! then on page 2 I get 13. 
You can see the blog at 
http://www.weddingdaydanceuk.co.uk/blog 
currently the page size is set to 14. 

Can you help with this very random issue?

**Comment by gigocabrera** [comment] 2015-12-03 16:08
HI @rogerg1967 I tried changing the page size on bloglist on a test 6.1.2 install and my personal produciton 6.2 install and it is working as expected. I was using the default template. Looks like you're using a custom template. Can you switch to the default template just for testing purposes

**Comment by rogerg1967** [comment] 2015-12-03 16:20
When I change the template to use bloglist I get this error:
Error: Object reference not set to an instance of an object.
In: at DotNetNuke.Modules.Blog.Entities.Blogs.BlogInfo.PermaLink(TabInfo tab) at DotNetNuke.Modules.Blog.Entities.Blogs.BlogInfo.GetProperty(String strPropertyName, String strFormat, CultureInfo formatProvider, UserInfo AccessingUser, Scope AccessLevel, Boolean& PropertyNotFound) at DotNetNuke.Modules.Blog.Templating.BaseCustomTokenReplace.replacedTokenValue(String strObjectName, String strPropertyName, String strFormat) at DotNetNuke.Modules.Blog.Templating.BaseTokenReplace.ReplaceTokenMatch(Match m) at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat) at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator) at DotNetNuke.Modules.Blog.Templating.GenericTokenReplace.ReplaceTokens(String strSourceText) at DotNetNuke.Modules.Blog.Templating.Template.ReplaceContents()

**Comment by gigocabrera** [comment] 2015-12-03 16:24
Are you using the latest build?

**Comment by rogerg1967** [comment] 2015-12-03 16:29
I have updated to 6.2

**Comment by gigocabrera** [comment] 2015-12-03 17:16
You are correct. I get the same error on the bloglist template on 6.2. This is definitely a bug. For now I would suggest using a different template and modifying it to your needs. If i come up with a workaround I'll post it here.

**Comment by donker** [comment] 2016-07-17 10:56
Is this resolved? If not: can someone give a simple description of the bug with maybe a path to reproduce that doesn't take me 10 hours to set up?

**Comment by valadas** [comment] 2018-10-28 04:40
I cannot reproduce and we got no reply since your comment in July, I am closing this @donker .

If you guys can reproduce in the latest build, please open a new issue.

**Closed by valadas** 2018-10-28 04:40 UTC
Labels: bug
